require('plugins.init')
--require('colorschemes.material')
require('buffer_line.bufferline')
require('settings.init')
require('lsp.init')
require('completion.init')
require('nvim_tree')
require('dashboard1')
require('treesitter')

